set_property LOC RAMB18_X11Y112 [get_cells io/hif_phy/hix_if/amif_core/rx_fec/r_s0log_reg]
set_property LOC RAMB18_X11Y113 [get_cells io/hif_phy/hix_if/amif_core/rx_fec/r_s1ilog_reg]
set_property LOC RAMB18_X11Y114 [get_cells io/hif_phy/hix_if/amif_core/rx_fec/r_errlog_reg]
set_property LOC RAMB36_X11Y58 [get_cells io/hif_phy/hix_if/amif_core/vqi/g3a.bram/infer.mem_reg_0]
set_property LOC RAMB36_X11Y59 [get_cells io/hif_phy/hix_if/amif_core/vqi/g3a.bram/infer.mem_reg_1]
set_property LOC RAMB36_X11Y60 [get_cells io/hif_phy/hix_if/amif_core/vqi/g3a.bram/infer.mem_reg_2]
set_property LOC RAMB36_X11Y61 [get_cells io/hif_phy/hix_if/amif_core/vqi/g3a.bram/infer.mem_reg_3]
set_property LOC RAMB36_X11Y62 [get_cells io/hif_phy/hix_if/amif_core/vqo/g3a.bram/infer.mem_reg_0]
set_property LOC RAMB36_X11Y63 [get_cells io/hif_phy/hix_if/amif_core/vqo/g3a.bram/infer.mem_reg_1]
set_property LOC RAMB36_X11Y64 [get_cells io/hif_phy/hix_if/amif_core/vqo/g3a.bram/infer.mem_reg_2]
set_property LOC RAMB36_X11Y65 [get_cells io/hif_phy/hix_if/amif_core/vqo/g3a.bram/infer.mem_reg_3]

########################################
# RESET
########################################
#set_property LOC BUFGCTRL_X0Y8  [get_cells -hier -regexp ae3/.*cae_pers/rsttop_bufg]
#set_property LOC BUFGCTRL_X0Y7  [get_cells -hier -regexp ae2/.*cae_pers/rsttop_bufg]
#set_property LOC BUFGCTRL_X0Y6  [get_cells -hier -regexp ae1/.*cae_pers/rsttop_bufg]
set_property LOC BUFGCTRL_X0Y5  [get_cells -hier -regexp ae0/.*cae_pers/rsttop_bufg]

#set_property LOC SLICE_X105Y247 [get_cells -hier -regexp ae3/.*cae_pers/dis/r_st_idle_reg]
#set_property LOC SLICE_X105Y247 [get_cells -hier -regexp ae2/.*cae_pers/dis/r_st_idle_reg]
#set_property LOC SLICE_X105Y247 [get_cells -hier -regexp ae1/.*cae_pers/dis/r_st_idle_reg]
set_property LOC SLICE_X105Y247 [get_cells -hier -regexp ae0/.*cae_pers/dis/r_st_idle_reg]

########################################
# Design specific
########################################
set_property LOC RAMB36_X5Y25 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$0/mem_reg_0}]
set_property LOC RAMB36_X5Y26 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$0/mem_reg_1}]
set_property LOC RAMB36_X5Y27 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$1/mem_reg_0}]
set_property LOC RAMB36_X5Y28 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$1/mem_reg_1}]
set_property LOC RAMB36_X5Y29 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$2/mem_reg_0}]
set_property LOC RAMB36_X5Y30 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$2/mem_reg_1}]
set_property LOC RAMB36_X5Y31 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$3/mem_reg_0}]
set_property LOC RAMB36_X5Y32 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$3/mem_reg_1}]
set_property LOC RAMB36_X6Y25 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$4/mem_reg_0}]
set_property LOC RAMB36_X6Y26 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$4/mem_reg_1}]
set_property LOC RAMB36_X6Y27 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$5/mem_reg_0}]
set_property LOC RAMB36_X6Y28 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$5/mem_reg_1}]
set_property LOC RAMB36_X6Y29 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$6/mem_reg_0}]
set_property LOC RAMB36_X6Y30 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$6/mem_reg_1}]
set_property LOC RAMB36_X6Y31 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$7/mem_reg_0}]
set_property LOC RAMB36_X6Y32 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colData$7/mem_reg_1}]
set_property LOC RAMB36_X4Y31 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colRslt/mem_reg_0}]
set_property LOC RAMB36_X4Y32 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colRslt/mem_reg_1}]
set_property LOC RAMB36_X4Y33 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colRslt/mem_reg_2}]
set_property LOC RAMB36_X4Y34 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_colRslt/mem_reg_3}]
set_property LOC RAMB36_X4Y25 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_pntWghtIdx/mem_reg_0}]
set_property LOC RAMB36_X4Y26 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_pntWghtIdx/mem_reg_1}]
set_property LOC RAMB36_X4Y27 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_pntWghtList$0/mem_reg}]
set_property LOC RAMB36_X4Y28 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_pntWghtList$1/mem_reg}]
set_property LOC RAMB36_X4Y29 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_pntWghtList$2/mem_reg}]
set_property LOC RAMB36_X4Y30 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_pntWghtList$3/mem_reg}]
set_property LOC RAMB36_X5Y33 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_pntWghtOut/mem_reg}]
set_property LOC RAMB36_X5Y34 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$0/m_transBuf/mem_reg}]

set_property LOC RAMB36_X2Y25 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$0/mem_reg_0}]
set_property LOC RAMB36_X2Y26 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$0/mem_reg_1}]
set_property LOC RAMB36_X2Y27 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$1/mem_reg_0}]
set_property LOC RAMB36_X2Y28 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$1/mem_reg_1}]
set_property LOC RAMB36_X2Y29 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$2/mem_reg_0}]
set_property LOC RAMB36_X2Y30 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$2/mem_reg_1}]
set_property LOC RAMB36_X2Y31 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$3/mem_reg_0}]
set_property LOC RAMB36_X2Y32 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$3/mem_reg_1}]
set_property LOC RAMB36_X1Y25 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$4/mem_reg_0}]
set_property LOC RAMB36_X1Y26 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$4/mem_reg_1}]
set_property LOC RAMB36_X1Y27 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$5/mem_reg_0}]
set_property LOC RAMB36_X1Y28 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$5/mem_reg_1}]
set_property LOC RAMB36_X1Y29 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$6/mem_reg_0}]
set_property LOC RAMB36_X1Y30 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$6/mem_reg_1}]
set_property LOC RAMB36_X1Y31 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$7/mem_reg_0}]
set_property LOC RAMB36_X1Y32 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colData$7/mem_reg_1}]
set_property LOC RAMB36_X3Y31 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colRslt/mem_reg_0}]
set_property LOC RAMB36_X3Y32 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colRslt/mem_reg_1}]
set_property LOC RAMB36_X3Y33 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colRslt/mem_reg_2}]
set_property LOC RAMB36_X3Y34 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_colRslt/mem_reg_3}]
set_property LOC RAMB36_X3Y25 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_pntWghtIdx/mem_reg_0}]
set_property LOC RAMB36_X3Y26 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_pntWghtIdx/mem_reg_1}]
set_property LOC RAMB36_X3Y27 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_pntWghtList$0/mem_reg}]
set_property LOC RAMB36_X3Y28 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_pntWghtList$1/mem_reg}]
set_property LOC RAMB36_X3Y29 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_pntWghtList$2/mem_reg}]
set_property LOC RAMB36_X3Y30 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_pntWghtList$3/mem_reg}]
set_property LOC RAMB36_X2Y33 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_pntWghtOut/mem_reg}]
set_property LOC RAMB36_X2Y34 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$1/m_transBuf/mem_reg}]

set_property LOC RAMB36_X5Y35 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$0/mem_reg_0}]
set_property LOC RAMB36_X5Y36 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$0/mem_reg_1}]
set_property LOC RAMB36_X5Y37 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$1/mem_reg_0}]
set_property LOC RAMB36_X5Y38 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$1/mem_reg_1}]
set_property LOC RAMB36_X5Y39 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$2/mem_reg_0}]
set_property LOC RAMB36_X5Y40 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$2/mem_reg_1}]
set_property LOC RAMB36_X5Y41 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$3/mem_reg_0}]
set_property LOC RAMB36_X5Y42 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$3/mem_reg_1}]
set_property LOC RAMB36_X6Y35 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$4/mem_reg_0}]
set_property LOC RAMB36_X6Y36 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$4/mem_reg_1}]
set_property LOC RAMB36_X6Y37 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$5/mem_reg_0}]
set_property LOC RAMB36_X6Y38 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$5/mem_reg_1}]
set_property LOC RAMB36_X6Y39 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$6/mem_reg_0}]
set_property LOC RAMB36_X6Y40 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$6/mem_reg_1}]
set_property LOC RAMB36_X6Y41 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$7/mem_reg_0}]
set_property LOC RAMB36_X6Y42 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colData$7/mem_reg_1}]
set_property LOC RAMB36_X4Y41 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colRslt/mem_reg_0}]
set_property LOC RAMB36_X4Y42 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colRslt/mem_reg_1}]
set_property LOC RAMB36_X4Y43 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colRslt/mem_reg_2}]
set_property LOC RAMB36_X4Y44 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_colRslt/mem_reg_3}]
set_property LOC RAMB36_X4Y35 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_pntWghtIdx/mem_reg_0}]
set_property LOC RAMB36_X4Y36 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_pntWghtIdx/mem_reg_1}]
set_property LOC RAMB36_X4Y37 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_pntWghtList$0/mem_reg}]
set_property LOC RAMB36_X4Y38 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_pntWghtList$1/mem_reg}]
set_property LOC RAMB36_X4Y39 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_pntWghtList$2/mem_reg}]
set_property LOC RAMB36_X4Y40 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_pntWghtList$3/mem_reg}]
set_property LOC RAMB36_X5Y43 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_pntWghtOut/mem_reg}]
set_property LOC RAMB36_X5Y44 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$2/m_transBuf/mem_reg}]

set_property LOC RAMB36_X2Y35 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$0/mem_reg_0}]
set_property LOC RAMB36_X2Y36 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$0/mem_reg_1}]
set_property LOC RAMB36_X2Y37 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$1/mem_reg_0}]
set_property LOC RAMB36_X2Y38 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$1/mem_reg_1}]
set_property LOC RAMB36_X2Y39 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$2/mem_reg_0}]
set_property LOC RAMB36_X2Y40 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$2/mem_reg_1}]
set_property LOC RAMB36_X2Y41 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$3/mem_reg_0}]
set_property LOC RAMB36_X2Y42 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$3/mem_reg_1}]
set_property LOC RAMB36_X1Y35 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$4/mem_reg_0}]
set_property LOC RAMB36_X1Y36 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$4/mem_reg_1}]
set_property LOC RAMB36_X1Y37 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$5/mem_reg_0}]
set_property LOC RAMB36_X1Y38 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$5/mem_reg_1}]
set_property LOC RAMB36_X1Y39 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$6/mem_reg_0}]
set_property LOC RAMB36_X1Y40 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$6/mem_reg_1}]
set_property LOC RAMB36_X1Y41 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$7/mem_reg_0}]
set_property LOC RAMB36_X1Y42 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colData$7/mem_reg_1}]
set_property LOC RAMB36_X3Y41 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colRslt/mem_reg_0}]
set_property LOC RAMB36_X3Y42 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colRslt/mem_reg_1}]
set_property LOC RAMB36_X3Y43 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colRslt/mem_reg_2}]
set_property LOC RAMB36_X3Y44 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_colRslt/mem_reg_3}]
set_property LOC RAMB36_X3Y35 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_pntWghtIdx/mem_reg_0}]
set_property LOC RAMB36_X3Y36 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_pntWghtIdx/mem_reg_1}]
set_property LOC RAMB36_X3Y37 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_pntWghtList$0/mem_reg}]
set_property LOC RAMB36_X3Y38 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_pntWghtList$1/mem_reg}]
set_property LOC RAMB36_X3Y39 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_pntWghtList$2/mem_reg}]
set_property LOC RAMB36_X3Y40 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_pntWghtList$3/mem_reg}]
set_property LOC RAMB36_X2Y43 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_pntWghtOut/mem_reg}]
set_property LOC RAMB36_X2Y44 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersHwrk$3/m_transBuf/mem_reg}]

set_property LOC RAMB18_X6Y16 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_huffCode$0/mem_reg}]
set_property LOC RAMB18_X6Y15 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_maxCode$0/mem_reg}]
set_property LOC RAMB18_X6Y14 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_lookup$0/mem_reg}]
set_property LOC RAMB18_X6Y17 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_valOff$0/mem_reg}]
set_property LOC RAMB18_X7Y16 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_huffCode$1/mem_reg}]
set_property LOC RAMB18_X7Y15 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_maxCode$1/mem_reg}]
set_property LOC RAMB18_X7Y14 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_lookup$1/mem_reg}]
set_property LOC RAMB18_X7Y17 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_valOff$1/mem_reg}]
set_property LOC RAMB18_X6Y20 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_huffCode$2/mem_reg}]
set_property LOC RAMB18_X6Y19 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_maxCode$2/mem_reg}]
set_property LOC RAMB18_X6Y18 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_lookup$2/mem_reg}]
set_property LOC RAMB18_X6Y21 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_valOff$2/mem_reg}]
set_property LOC RAMB18_X7Y20 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_huffCode$3/mem_reg}]
set_property LOC RAMB18_X7Y19 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_maxCode$3/mem_reg}]
set_property LOC RAMB18_X7Y18 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_lookup$3/mem_reg}]
set_property LOC RAMB18_X7Y21 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_valOff$3/mem_reg}]
set_property LOC RAMB18_X6Y24 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_huffCode$4/mem_reg}]
set_property LOC RAMB18_X6Y23 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_maxCode$4/mem_reg}]
set_property LOC RAMB18_X6Y22 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_lookup$4/mem_reg}]
set_property LOC RAMB18_X6Y25 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_valOff$4/mem_reg}]
set_property LOC RAMB18_X7Y24 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_huffCode$5/mem_reg}]
set_property LOC RAMB18_X7Y23 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_maxCode$5/mem_reg}]
set_property LOC RAMB18_X7Y22 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_lookup$5/mem_reg}]
set_property LOC RAMB18_X7Y25 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$0/m_valOff$5/mem_reg}]

set_property LOC RAMB18_X4Y16 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_huffCode$0/mem_reg}]
set_property LOC RAMB18_X4Y15 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_maxCode$0/mem_reg}]
set_property LOC RAMB18_X4Y14 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_lookup$0/mem_reg}]
set_property LOC RAMB18_X4Y17 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_valOff$0/mem_reg}]
set_property LOC RAMB18_X3Y16 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_huffCode$1/mem_reg}]
set_property LOC RAMB18_X3Y15 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_maxCode$1/mem_reg}]
set_property LOC RAMB18_X3Y14 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_lookup$1/mem_reg}]
set_property LOC RAMB18_X3Y17 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_valOff$1/mem_reg}]
set_property LOC RAMB18_X4Y20 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_huffCode$2/mem_reg}]
set_property LOC RAMB18_X4Y19 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_maxCode$2/mem_reg}]
set_property LOC RAMB18_X4Y18 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_lookup$2/mem_reg}]
set_property LOC RAMB18_X4Y21 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_valOff$2/mem_reg}]
set_property LOC RAMB18_X3Y20 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_huffCode$3/mem_reg}]
set_property LOC RAMB18_X3Y19 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_maxCode$3/mem_reg}]
set_property LOC RAMB18_X3Y18 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_lookup$3/mem_reg}]
set_property LOC RAMB18_X3Y21 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_valOff$3/mem_reg}]
set_property LOC RAMB18_X4Y24 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_huffCode$4/mem_reg}]
set_property LOC RAMB18_X4Y23 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_maxCode$4/mem_reg}]
set_property LOC RAMB18_X4Y22 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_lookup$4/mem_reg}]
set_property LOC RAMB18_X4Y25 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_valOff$4/mem_reg}]
set_property LOC RAMB18_X3Y24 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_huffCode$5/mem_reg}]
set_property LOC RAMB18_X3Y23 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_maxCode$5/mem_reg}]
set_property LOC RAMB18_X3Y22 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_lookup$5/mem_reg}]
set_property LOC RAMB18_X3Y25 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$1/m_valOff$5/mem_reg}]

set_property LOC RAMB18_X6Y36 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_huffCode$0/mem_reg}]
set_property LOC RAMB18_X6Y35 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_maxCode$0/mem_reg}]
set_property LOC RAMB18_X6Y34 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_lookup$0/mem_reg}]
set_property LOC RAMB18_X6Y37 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_valOff$0/mem_reg}]
set_property LOC RAMB18_X7Y36 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_huffCode$1/mem_reg}]
set_property LOC RAMB18_X7Y35 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_maxCode$1/mem_reg}]
set_property LOC RAMB18_X7Y34 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_lookup$1/mem_reg}]
set_property LOC RAMB18_X7Y37 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_valOff$1/mem_reg}]
set_property LOC RAMB18_X6Y40 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_huffCode$2/mem_reg}]
set_property LOC RAMB18_X6Y39 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_maxCode$2/mem_reg}]
set_property LOC RAMB18_X6Y38 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_lookup$2/mem_reg}]
set_property LOC RAMB18_X6Y41 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_valOff$2/mem_reg}]
set_property LOC RAMB18_X7Y40 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_huffCode$3/mem_reg}]
set_property LOC RAMB18_X7Y39 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_maxCode$3/mem_reg}]
set_property LOC RAMB18_X7Y38 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_lookup$3/mem_reg}]
set_property LOC RAMB18_X7Y41 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_valOff$3/mem_reg}]
set_property LOC RAMB18_X6Y44 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_huffCode$4/mem_reg}]
set_property LOC RAMB18_X6Y43 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_maxCode$4/mem_reg}]
set_property LOC RAMB18_X6Y42 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_lookup$4/mem_reg}]
set_property LOC RAMB18_X6Y45 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_valOff$4/mem_reg}]
set_property LOC RAMB18_X7Y44 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_huffCode$5/mem_reg}]
set_property LOC RAMB18_X7Y43 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_maxCode$5/mem_reg}]
set_property LOC RAMB18_X7Y42 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_lookup$5/mem_reg}]
set_property LOC RAMB18_X7Y45 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$2/m_valOff$5/mem_reg}]

set_property LOC RAMB18_X4Y36 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_huffCode$0/mem_reg}]
set_property LOC RAMB18_X4Y35 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_maxCode$0/mem_reg}]
set_property LOC RAMB18_X4Y34 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_lookup$0/mem_reg}]
set_property LOC RAMB18_X4Y37 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_valOff$0/mem_reg}]
set_property LOC RAMB18_X3Y36 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_huffCode$1/mem_reg}]
set_property LOC RAMB18_X3Y35 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_maxCode$1/mem_reg}]
set_property LOC RAMB18_X3Y34 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_lookup$1/mem_reg}]
set_property LOC RAMB18_X3Y37 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_valOff$1/mem_reg}]
set_property LOC RAMB18_X4Y40 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_huffCode$2/mem_reg}]
set_property LOC RAMB18_X4Y39 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_maxCode$2/mem_reg}]
set_property LOC RAMB18_X4Y38 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_lookup$2/mem_reg}]
set_property LOC RAMB18_X4Y41 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_valOff$2/mem_reg}]
set_property LOC RAMB18_X3Y40 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_huffCode$3/mem_reg}]
set_property LOC RAMB18_X3Y39 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_maxCode$3/mem_reg}]
set_property LOC RAMB18_X3Y38 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_lookup$3/mem_reg}]
set_property LOC RAMB18_X3Y41 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_valOff$3/mem_reg}]
set_property LOC RAMB18_X4Y44 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_huffCode$4/mem_reg}]
set_property LOC RAMB18_X4Y43 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_maxCode$4/mem_reg}]
set_property LOC RAMB18_X4Y42 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_lookup$4/mem_reg}]
set_property LOC RAMB18_X4Y45 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_valOff$4/mem_reg}]
set_property LOC RAMB18_X2Y44 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_huffCode$5/mem_reg}]
set_property LOC RAMB18_X2Y43 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_maxCode$5/mem_reg}]
set_property LOC RAMB18_X2Y42 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_lookup$5/mem_reg}]
set_property LOC RAMB18_X2Y45 [get_cells {ae0/cae0.cae_pers/top/pPersAuTop$0/pPersIhuf2$3/m_valOff$5/mem_reg}]
