#!/bin/sh

CFG="-c /hw/local/c5x/share/uncrustify/linux.cfg"
#CFG="-c /hw/local/c5x/share/uncrustify/google.cfg"

for f in $@
do
    dos2unix "$f"
    /hw/local/c5x/bin/uncrustify $CFG "$f"
    mv -f "$f.uncrustify" "$f"
    dos2unix "$f"
done
