export CNY_PDK_PLATFORM = wx2-vu7p

export CNY_HT_AEUCNT = 2

export CNY_NUM_IO_PORTS = 10
export CNY_IO_PORTS_WIDTH = 128
export CNY_EN_QSFP0_LANES = 4
export CNY_EN_QSFP1_LANES = 4


export CFLAGS += -std=c++11

export CNY_HT_PDK_CFG = scripts/config.pdk

include ../Makefile.template
