
####################################################################
# Include Convey Makefile Template
####################################################################
include ../config.pdk

SILENT ?= .SILENT   # Allow Override of Silent

$(SILENT):
